version: '3.4'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx
    restart: always   
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro 
    ports:
      - 80:80
      - 443:443
    networks:
        my-network-name:
            aliases:
                - proxy-name
---
  PaperBoy.webapi:
    image: paperboy.webapi
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      PaperBoy.db:
        condition: service_healthy
    environment:
      - VIRTUAL_HOST=webapi.localhost
    networks:
        my-network-name:
            aliases:
                - frontend-name
  PaperBoy.db:
    image: postgres:13.2
    hostname: 'PaperBoy.db'
    container_name: db
    environment:
      - POSTGRES_DB=paperboy
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./files/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
        my-network-name:
            aliases:
                - sql-name
networks:
    my-network-name: