version: '3.4'

services:
  PaperBoy.web:
    image: paperboy.web
    container_name: Web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      PaperBoy.db:
        condition: service_healthy

  PaperBoy.db:
    image: postgres:13.2
    hostname: 'PaperBoy.db'
    container_name: PaperBoy.db
    environment:
      - POSTGRES_DB=paperboy
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./files/db:/var/lib/postgresql/data
    ports:
      - 5432:5432