version: '3.4'

services:
  PaperBoy.webapi:
    image: paperboy.webapi
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PASSWORD_ENV_SEEDED=81c145ce-e510-4521-b641-ae67815f9145
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      PaperBoy.db:
        condition: service_healthy

  PaperBoy.db:
    image: postgres:13.2
    hostname: 'PaperBoy.db'
    container_name: db
    environment:
      - POSTGRES_DB=paperboy
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./files/db:/var/lib/postgresql/data
    ports:
      - 5432:5432